services:
    postgres:
        image: postgres:14
        environment:
            - POSTGRES_DB=store_db
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=123456
        ports:
            - '5432:5432'
        volumes:
            - ./postgres_data:/var/lib/postgresql/data
volumes:
    postgres_data: {}
